// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_message_lite2.proto

package com.google.common.truth.extensions.proto;

/**
 * Protobuf type {@code com.google.common.truth.extensions.proto.OtherTestMessageLite2}
 */
public  final class OtherTestMessageLite2 extends
    com.google.protobuf.GeneratedMessageLite<
        OtherTestMessageLite2, OtherTestMessageLite2.Builder> implements
    // @@protoc_insertion_point(message_implements:com.google.common.truth.extensions.proto.OtherTestMessageLite2)
    OtherTestMessageLite2OrBuilder {
  private OtherTestMessageLite2() {
  }
  private int bitField0_;
  public static final int OPTIONAL_INT_FIELD_NUMBER = 1;
  private int optionalInt_;
  /**
   * <code>optional int32 optional_int = 1;</code>
   * @return Whether the optionalInt field is set.
   */
  @java.lang.Override
  public boolean hasOptionalInt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 optional_int = 1;</code>
   * @return The optionalInt.
   */
  @java.lang.Override
  public int getOptionalInt() {
    return optionalInt_;
  }
  /**
   * <code>optional int32 optional_int = 1;</code>
   * @param value The optionalInt to set.
   */
  private void setOptionalInt(int value) {
    bitField0_ |= 0x00000001;
    optionalInt_ = value;
  }
  /**
   * <code>optional int32 optional_int = 1;</code>
   */
  private void clearOptionalInt() {
    bitField0_ = (bitField0_ & ~0x00000001);
    optionalInt_ = 0;
  }

  public static com.google.common.truth.extensions.proto.OtherTestMessageLite2 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.common.truth.extensions.proto.OtherTestMessageLite2 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.OtherTestMessageLite2 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.common.truth.extensions.proto.OtherTestMessageLite2 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.OtherTestMessageLite2 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.common.truth.extensions.proto.OtherTestMessageLite2 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.OtherTestMessageLite2 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.common.truth.extensions.proto.OtherTestMessageLite2 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.OtherTestMessageLite2 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.common.truth.extensions.proto.OtherTestMessageLite2 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.OtherTestMessageLite2 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.common.truth.extensions.proto.OtherTestMessageLite2 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.google.common.truth.extensions.proto.OtherTestMessageLite2 prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.google.common.truth.extensions.proto.OtherTestMessageLite2}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.common.truth.extensions.proto.OtherTestMessageLite2, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.google.common.truth.extensions.proto.OtherTestMessageLite2)
      com.google.common.truth.extensions.proto.OtherTestMessageLite2OrBuilder {
    // Construct using com.google.common.truth.extensions.proto.OtherTestMessageLite2.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int32 optional_int = 1;</code>
     * @return Whether the optionalInt field is set.
     */
    @java.lang.Override
    public boolean hasOptionalInt() {
      return instance.hasOptionalInt();
    }
    /**
     * <code>optional int32 optional_int = 1;</code>
     * @return The optionalInt.
     */
    @java.lang.Override
    public int getOptionalInt() {
      return instance.getOptionalInt();
    }
    /**
     * <code>optional int32 optional_int = 1;</code>
     * @param value The optionalInt to set.
     * @return This builder for chaining.
     */
    public Builder setOptionalInt(int value) {
      copyOnWrite();
      instance.setOptionalInt(value);
      return this;
    }
    /**
     * <code>optional int32 optional_int = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOptionalInt() {
      copyOnWrite();
      instance.clearOptionalInt();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.google.common.truth.extensions.proto.OtherTestMessageLite2)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.common.truth.extensions.proto.OtherTestMessageLite2();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "optionalInt_",
          };
          java.lang.String info =
              "\u0001\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1004\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.google.common.truth.extensions.proto.OtherTestMessageLite2> parser = PARSER;
        if (parser == null) {
          synchronized (com.google.common.truth.extensions.proto.OtherTestMessageLite2.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.google.common.truth.extensions.proto.OtherTestMessageLite2>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.google.common.truth.extensions.proto.OtherTestMessageLite2)
  private static final com.google.common.truth.extensions.proto.OtherTestMessageLite2 DEFAULT_INSTANCE;
  static {
    OtherTestMessageLite2 defaultInstance = new OtherTestMessageLite2();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      OtherTestMessageLite2.class, defaultInstance);
  }

  public static com.google.common.truth.extensions.proto.OtherTestMessageLite2 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<OtherTestMessageLite2> PARSER;

  public static com.google.protobuf.Parser<OtherTestMessageLite2> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

