// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_message_lite3.proto

package com.google.common.truth.extensions.proto;

public interface OtherTestMessageLite3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.common.truth.extensions.proto.OtherTestMessageLite3)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 optional_int = 1;</code>
   * @return The optionalInt.
   */
  int getOptionalInt();
}
