// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_message_lite2.proto

package com.google.common.truth.extensions.proto;

public interface OtherTestMessageLite2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.common.truth.extensions.proto.OtherTestMessageLite2)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 optional_int = 1;</code>
   * @return Whether the optionalInt field is set.
   */
  boolean hasOptionalInt();
  /**
   * <code>optional int32 optional_int = 1;</code>
   * @return The optionalInt.
   */
  int getOptionalInt();
}
