// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_message_lite3.proto

package com.google.common.truth.extensions.proto;

public final class TestMessageLite3OuterClass {
  private TestMessageLite3OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
