// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_message_lite2.proto

package com.google.common.truth.extensions.proto;

public interface TestMessageLite2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.common.truth.extensions.proto.TestMessageLite2)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 optional_int = 1;</code>
   * @return Whether the optionalInt field is set.
   */
  boolean hasOptionalInt();
  /**
   * <code>optional int32 optional_int = 1;</code>
   * @return The optionalInt.
   */
  int getOptionalInt();

  /**
   * <code>optional .com.google.common.truth.extensions.proto.TestMessageLite2.SubMessage sub_message = 2;</code>
   * @return Whether the subMessage field is set.
   */
  boolean hasSubMessage();
  /**
   * <code>optional .com.google.common.truth.extensions.proto.TestMessageLite2.SubMessage sub_message = 2;</code>
   * @return The subMessage.
   */
  com.google.common.truth.extensions.proto.TestMessageLite2.SubMessage getSubMessage();
}
