// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_message_lite2.proto

package com.google.common.truth.extensions.proto;

public interface TestMessageLite2WithRequiredFieldsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required int32 required_int = 1;</code>
   * @return Whether the requiredInt field is set.
   */
  boolean hasRequiredInt();
  /**
   * <code>required int32 required_int = 1;</code>
   * @return The requiredInt.
   */
  int getRequiredInt();

  /**
   * <code>optional string optional_string = 2;</code>
   * @return Whether the optionalString field is set.
   */
  boolean hasOptionalString();
  /**
   * <code>optional string optional_string = 2;</code>
   * @return The optionalString.
   */
  java.lang.String getOptionalString();
  /**
   * <code>optional string optional_string = 2;</code>
   * @return The bytes for optionalString.
   */
  com.google.protobuf.ByteString
      getOptionalStringBytes();
}
