// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_message_lite3.proto

package com.google.common.truth.extensions.proto;

public interface TestMessageLite3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.common.truth.extensions.proto.TestMessageLite3)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 optional_int = 1;</code>
   * @return The optionalInt.
   */
  int getOptionalInt();

  /**
   * <code>.com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage sub_message = 2;</code>
   * @return Whether the subMessage field is set.
   */
  boolean hasSubMessage();
  /**
   * <code>.com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage sub_message = 2;</code>
   * @return The subMessage.
   */
  com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage getSubMessage();
}
