// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_message_lite3.proto

package com.google.common.truth.extensions.proto;

/**
 * Protobuf type {@code com.google.common.truth.extensions.proto.TestMessageLite3}
 */
public  final class TestMessageLite3 extends
    com.google.protobuf.GeneratedMessageLite<
        TestMessageLite3, TestMessageLite3.Builder> implements
    // @@protoc_insertion_point(message_implements:com.google.common.truth.extensions.proto.TestMessageLite3)
    TestMessageLite3OrBuilder {
  private TestMessageLite3() {
  }
  public interface SubMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string optional_string = 1;</code>
     * @return The optionalString.
     */
    java.lang.String getOptionalString();
    /**
     * <code>string optional_string = 1;</code>
     * @return The bytes for optionalString.
     */
    com.google.protobuf.ByteString
        getOptionalStringBytes();
  }
  /**
   * Protobuf type {@code com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage}
   */
  public  static final class SubMessage extends
      com.google.protobuf.GeneratedMessageLite<
          SubMessage, SubMessage.Builder> implements
      // @@protoc_insertion_point(message_implements:com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage)
      SubMessageOrBuilder {
    private SubMessage() {
      optionalString_ = "";
    }
    public static final int OPTIONAL_STRING_FIELD_NUMBER = 1;
    private java.lang.String optionalString_;
    /**
     * <code>string optional_string = 1;</code>
     * @return The optionalString.
     */
    @java.lang.Override
    public java.lang.String getOptionalString() {
      return optionalString_;
    }
    /**
     * <code>string optional_string = 1;</code>
     * @return The bytes for optionalString.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOptionalStringBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(optionalString_);
    }
    /**
     * <code>string optional_string = 1;</code>
     * @param value The optionalString to set.
     */
    private void setOptionalString(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      optionalString_ = value;
    }
    /**
     * <code>string optional_string = 1;</code>
     */
    private void clearOptionalString() {
      
      optionalString_ = getDefaultInstance().getOptionalString();
    }
    /**
     * <code>string optional_string = 1;</code>
     * @param value The bytes for optionalString to set.
     */
    private void setOptionalStringBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      optionalString_ = value.toStringUtf8();
      
    }

    public static com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage)
        com.google.common.truth.extensions.proto.TestMessageLite3.SubMessageOrBuilder {
      // Construct using com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string optional_string = 1;</code>
       * @return The optionalString.
       */
      @java.lang.Override
      public java.lang.String getOptionalString() {
        return instance.getOptionalString();
      }
      /**
       * <code>string optional_string = 1;</code>
       * @return The bytes for optionalString.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getOptionalStringBytes() {
        return instance.getOptionalStringBytes();
      }
      /**
       * <code>string optional_string = 1;</code>
       * @param value The optionalString to set.
       * @return This builder for chaining.
       */
      public Builder setOptionalString(
          java.lang.String value) {
        copyOnWrite();
        instance.setOptionalString(value);
        return this;
      }
      /**
       * <code>string optional_string = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOptionalString() {
        copyOnWrite();
        instance.clearOptionalString();
        return this;
      }
      /**
       * <code>string optional_string = 1;</code>
       * @param value The bytes for optionalString to set.
       * @return This builder for chaining.
       */
      public Builder setOptionalStringBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOptionalStringBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "optionalString_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage> parser = PARSER;
          if (parser == null) {
            synchronized (com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage)
    private static final com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage DEFAULT_INSTANCE;
    static {
      SubMessage defaultInstance = new SubMessage();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SubMessage.class, defaultInstance);
    }

    public static com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SubMessage> PARSER;

    public static com.google.protobuf.Parser<SubMessage> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public static final int OPTIONAL_INT_FIELD_NUMBER = 1;
  private int optionalInt_;
  /**
   * <code>int32 optional_int = 1;</code>
   * @return The optionalInt.
   */
  @java.lang.Override
  public int getOptionalInt() {
    return optionalInt_;
  }
  /**
   * <code>int32 optional_int = 1;</code>
   * @param value The optionalInt to set.
   */
  private void setOptionalInt(int value) {
    
    optionalInt_ = value;
  }
  /**
   * <code>int32 optional_int = 1;</code>
   */
  private void clearOptionalInt() {
    
    optionalInt_ = 0;
  }

  public static final int SUB_MESSAGE_FIELD_NUMBER = 2;
  private com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage subMessage_;
  /**
   * <code>.com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage sub_message = 2;</code>
   */
  @java.lang.Override
  public boolean hasSubMessage() {
    return subMessage_ != null;
  }
  /**
   * <code>.com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage sub_message = 2;</code>
   */
  @java.lang.Override
  public com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage getSubMessage() {
    return subMessage_ == null ? com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage.getDefaultInstance() : subMessage_;
  }
  /**
   * <code>.com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage sub_message = 2;</code>
   */
  private void setSubMessage(com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage value) {
    value.getClass();
  subMessage_ = value;
    
    }
  /**
   * <code>.com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage sub_message = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeSubMessage(com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage value) {
    value.getClass();
  if (subMessage_ != null &&
        subMessage_ != com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage.getDefaultInstance()) {
      subMessage_ =
        com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage.newBuilder(subMessage_).mergeFrom(value).buildPartial();
    } else {
      subMessage_ = value;
    }
    
  }
  /**
   * <code>.com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage sub_message = 2;</code>
   */
  private void clearSubMessage() {  subMessage_ = null;
    
  }

  public static com.google.common.truth.extensions.proto.TestMessageLite3 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite3 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite3 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite3 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite3 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite3 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite3 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite3 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite3 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite3 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite3 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite3 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.google.common.truth.extensions.proto.TestMessageLite3 prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.google.common.truth.extensions.proto.TestMessageLite3}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.common.truth.extensions.proto.TestMessageLite3, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.google.common.truth.extensions.proto.TestMessageLite3)
      com.google.common.truth.extensions.proto.TestMessageLite3OrBuilder {
    // Construct using com.google.common.truth.extensions.proto.TestMessageLite3.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int32 optional_int = 1;</code>
     * @return The optionalInt.
     */
    @java.lang.Override
    public int getOptionalInt() {
      return instance.getOptionalInt();
    }
    /**
     * <code>int32 optional_int = 1;</code>
     * @param value The optionalInt to set.
     * @return This builder for chaining.
     */
    public Builder setOptionalInt(int value) {
      copyOnWrite();
      instance.setOptionalInt(value);
      return this;
    }
    /**
     * <code>int32 optional_int = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOptionalInt() {
      copyOnWrite();
      instance.clearOptionalInt();
      return this;
    }

    /**
     * <code>.com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage sub_message = 2;</code>
     */
    @java.lang.Override
    public boolean hasSubMessage() {
      return instance.hasSubMessage();
    }
    /**
     * <code>.com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage sub_message = 2;</code>
     */
    @java.lang.Override
    public com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage getSubMessage() {
      return instance.getSubMessage();
    }
    /**
     * <code>.com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage sub_message = 2;</code>
     */
    public Builder setSubMessage(com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage value) {
      copyOnWrite();
      instance.setSubMessage(value);
      return this;
      }
    /**
     * <code>.com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage sub_message = 2;</code>
     */
    public Builder setSubMessage(
        com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage.Builder builderForValue) {
      copyOnWrite();
      instance.setSubMessage(builderForValue.build());
      return this;
    }
    /**
     * <code>.com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage sub_message = 2;</code>
     */
    public Builder mergeSubMessage(com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage value) {
      copyOnWrite();
      instance.mergeSubMessage(value);
      return this;
    }
    /**
     * <code>.com.google.common.truth.extensions.proto.TestMessageLite3.SubMessage sub_message = 2;</code>
     */
    public Builder clearSubMessage() {  copyOnWrite();
      instance.clearSubMessage();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.google.common.truth.extensions.proto.TestMessageLite3)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.common.truth.extensions.proto.TestMessageLite3();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "optionalInt_",
            "subMessage_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\t" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.google.common.truth.extensions.proto.TestMessageLite3> parser = PARSER;
        if (parser == null) {
          synchronized (com.google.common.truth.extensions.proto.TestMessageLite3.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.google.common.truth.extensions.proto.TestMessageLite3>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.google.common.truth.extensions.proto.TestMessageLite3)
  private static final com.google.common.truth.extensions.proto.TestMessageLite3 DEFAULT_INSTANCE;
  static {
    TestMessageLite3 defaultInstance = new TestMessageLite3();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      TestMessageLite3.class, defaultInstance);
  }

  public static com.google.common.truth.extensions.proto.TestMessageLite3 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TestMessageLite3> PARSER;

  public static com.google.protobuf.Parser<TestMessageLite3> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

