// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_message_lite2.proto

package com.google.common.truth.extensions.proto;

/**
 * Protobuf type {@code com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields}
 */
public  final class TestMessageLite2WithRequiredFields extends
    com.google.protobuf.GeneratedMessageLite<
        TestMessageLite2WithRequiredFields, TestMessageLite2WithRequiredFields.Builder> implements
    // @@protoc_insertion_point(message_implements:com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields)
    TestMessageLite2WithRequiredFieldsOrBuilder {
  private TestMessageLite2WithRequiredFields() {
    optionalString_ = "";
  }
  private int bitField0_;
  public static final int REQUIRED_INT_FIELD_NUMBER = 1;
  private int requiredInt_;
  /**
   * <code>required int32 required_int = 1;</code>
   * @return Whether the requiredInt field is set.
   */
  @java.lang.Override
  public boolean hasRequiredInt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int32 required_int = 1;</code>
   * @return The requiredInt.
   */
  @java.lang.Override
  public int getRequiredInt() {
    return requiredInt_;
  }
  /**
   * <code>required int32 required_int = 1;</code>
   * @param value The requiredInt to set.
   */
  private void setRequiredInt(int value) {
    bitField0_ |= 0x00000001;
    requiredInt_ = value;
  }
  /**
   * <code>required int32 required_int = 1;</code>
   */
  private void clearRequiredInt() {
    bitField0_ = (bitField0_ & ~0x00000001);
    requiredInt_ = 0;
  }

  public static final int OPTIONAL_STRING_FIELD_NUMBER = 2;
  private java.lang.String optionalString_;
  /**
   * <code>optional string optional_string = 2;</code>
   * @return Whether the optionalString field is set.
   */
  @java.lang.Override
  public boolean hasOptionalString() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string optional_string = 2;</code>
   * @return The optionalString.
   */
  @java.lang.Override
  public java.lang.String getOptionalString() {
    return optionalString_;
  }
  /**
   * <code>optional string optional_string = 2;</code>
   * @return The bytes for optionalString.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOptionalStringBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(optionalString_);
  }
  /**
   * <code>optional string optional_string = 2;</code>
   * @param value The optionalString to set.
   */
  private void setOptionalString(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
    optionalString_ = value;
  }
  /**
   * <code>optional string optional_string = 2;</code>
   */
  private void clearOptionalString() {
    bitField0_ = (bitField0_ & ~0x00000002);
    optionalString_ = getDefaultInstance().getOptionalString();
  }
  /**
   * <code>optional string optional_string = 2;</code>
   * @param value The bytes for optionalString to set.
   */
  private void setOptionalStringBytes(
      com.google.protobuf.ByteString value) {
    optionalString_ = value.toStringUtf8();
    bitField0_ |= 0x00000002;
  }

  public static com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields)
      com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFieldsOrBuilder {
    // Construct using com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>required int32 required_int = 1;</code>
     * @return Whether the requiredInt field is set.
     */
    @java.lang.Override
    public boolean hasRequiredInt() {
      return instance.hasRequiredInt();
    }
    /**
     * <code>required int32 required_int = 1;</code>
     * @return The requiredInt.
     */
    @java.lang.Override
    public int getRequiredInt() {
      return instance.getRequiredInt();
    }
    /**
     * <code>required int32 required_int = 1;</code>
     * @param value The requiredInt to set.
     * @return This builder for chaining.
     */
    public Builder setRequiredInt(int value) {
      copyOnWrite();
      instance.setRequiredInt(value);
      return this;
    }
    /**
     * <code>required int32 required_int = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequiredInt() {
      copyOnWrite();
      instance.clearRequiredInt();
      return this;
    }

    /**
     * <code>optional string optional_string = 2;</code>
     * @return Whether the optionalString field is set.
     */
    @java.lang.Override
    public boolean hasOptionalString() {
      return instance.hasOptionalString();
    }
    /**
     * <code>optional string optional_string = 2;</code>
     * @return The optionalString.
     */
    @java.lang.Override
    public java.lang.String getOptionalString() {
      return instance.getOptionalString();
    }
    /**
     * <code>optional string optional_string = 2;</code>
     * @return The bytes for optionalString.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOptionalStringBytes() {
      return instance.getOptionalStringBytes();
    }
    /**
     * <code>optional string optional_string = 2;</code>
     * @param value The optionalString to set.
     * @return This builder for chaining.
     */
    public Builder setOptionalString(
        java.lang.String value) {
      copyOnWrite();
      instance.setOptionalString(value);
      return this;
    }
    /**
     * <code>optional string optional_string = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOptionalString() {
      copyOnWrite();
      instance.clearOptionalString();
      return this;
    }
    /**
     * <code>optional string optional_string = 2;</code>
     * @param value The bytes for optionalString to set.
     * @return This builder for chaining.
     */
    public Builder setOptionalStringBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOptionalStringBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "requiredInt_",
            "optionalString_",
          };
          java.lang.String info =
              "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0001\u0001\u1504\u0000\u0002" +
              "\u1008\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields> parser = PARSER;
        if (parser == null) {
          synchronized (com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields)
  private static final com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields DEFAULT_INSTANCE;
  static {
    TestMessageLite2WithRequiredFields defaultInstance = new TestMessageLite2WithRequiredFields();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      TestMessageLite2WithRequiredFields.class, defaultInstance);
  }

  public static com.google.common.truth.extensions.proto.TestMessageLite2WithRequiredFields getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TestMessageLite2WithRequiredFields> PARSER;

  public static com.google.protobuf.Parser<TestMessageLite2WithRequiredFields> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

